import { Link } from 'react-router-dom'
import { useState, useEffect } from 'react'
import axios from 'axios'

const API_BASE = '/api'

function LandingPage() {
    const [stats, setStats] = useState({ matchCount: 0, teamCount: 0 })

    useEffect(() => {
        Promise.all([
            axios.get(`${API_BASE}/matches`),
            axios.get(`${API_BASE}/table`)
        ]).then(([matchesRes, tableRes]) => {
            setStats({
                matchCount: matchesRes.data.length,
                teamCount: tableRes.data.length
            })
        }).catch(console.error)
    }, [])

    const features = [
        {
            icon: '🎯',
            title: 'Predicted Scores',
            description: 'AI-powered match predictions based on comprehensive statistical analysis'
        },
        {
            icon: '📊',
            title: 'Confidence Levels',
            description: 'Transparency in predictions with confidence percentages for each analysis'
        },
        {
            icon: '🤖',
            title: 'AI Scenarios',
            description: 'Detailed match scenarios generated by advanced language models'
        },
        {
            icon: '⚡',
            title: 'Key Players',
            description: 'Identification of crucial players who can decide the outcome'
        },
        {
            icon: '📈',
            title: 'Form Analysis',
            description: 'Last 5 games breakdown for both teams including xG statistics'
        },
        {
            icon: '🏆',
            title: 'League Table',
            description: 'Real-time standings with advanced metrics and team comparisons'
        }
    ]

    return (
        <div className="animate-fade-in">
            {/* Hero Section */}
            <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-slate-800 via-slate-900 to-emerald-900 mb-12">
                <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA2MCA2MCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPjxwYXRoIGQ9Ik0zNiAxOGMtNi42MjcgMC0xMiA1LjM3My0xMiAxMnM1LjM3MyAxMiAxMiAxMiAxMi01LjM3MyAxMi0xMi01LjM3My0xMi0xMi0xMnoiIHN0cm9rZT0iIzEwYjk4MSIgc3Ryb2tlLW9wYWNpdHk9Ii4xIi8+PC9nPjwvc3ZnPg==')] opacity-20"></div>
                <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-emerald-500 via-cyan-500 to-emerald-500"></div>

                <div className="relative px-8 py-20 text-center">
                    <div className="inline-flex items-center px-4 py-2 rounded-full bg-emerald-500/10 border border-emerald-500/20 mb-6">
                        <span className="text-emerald-400 text-sm font-medium">🧠 Powered by AI Analytics</span>
                    </div>

                    <h1 className="text-5xl md:text-6xl font-black text-white mb-6 leading-tight">
                        Football Match
                        <span className="block bg-gradient-to-r from-emerald-400 to-cyan-400 bg-clip-text text-transparent">
                            Intelligence
                        </span>
                    </h1>

                    <p className="text-xl text-gray-400 max-w-2xl mx-auto mb-10">
                        Advanced AI predictions, statistical analysis, and expert insights for Premier League matches.
                        Make informed decisions with confidence.
                    </p>

                    <div className="flex flex-wrap justify-center gap-4">
                        <Link
                            to="/matches"
                            className="px-8 py-4 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xl transition-all shadow-xl shadow-emerald-900/50 hover:shadow-emerald-800/50 hover:-translate-y-1"
                        >
                            View Matches →
                        </Link>
                        <Link
                            to="/table"
                            className="px-8 py-4 bg-slate-700 hover:bg-slate-600 text-white font-bold rounded-xl transition-all hover:-translate-y-1"
                        >
                            League Table
                        </Link>
                    </div>
                </div>
            </div>

            {/* Stats Bar */}
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-12">
                <div className="bg-slate-800 rounded-xl p-6 text-center border border-slate-700">
                    <div className="text-3xl font-black text-emerald-400">{stats.matchCount}</div>
                    <div className="text-sm text-gray-400">Upcoming Matches</div>
                </div>
                <div className="bg-slate-800 rounded-xl p-6 text-center border border-slate-700">
                    <div className="text-3xl font-black text-cyan-400">{stats.teamCount}</div>
                    <div className="text-sm text-gray-400">Teams Tracked</div>
                </div>
                <div className="bg-slate-800 rounded-xl p-6 text-center border border-slate-700">
                    <div className="text-3xl font-black text-purple-400">AI</div>
                    <div className="text-sm text-gray-400">Powered Analysis</div>
                </div>
                <div className="bg-slate-800 rounded-xl p-6 text-center border border-slate-700">
                    <div className="text-3xl font-black text-yellow-400">Live</div>
                    <div className="text-sm text-gray-400">Data Updates</div>
                </div>
            </div>

            {/* Features Grid */}
            <h2 className="text-2xl font-bold text-white mb-6 flex items-center">
                <span className="bg-emerald-500 w-1 h-8 mr-3 rounded-full"></span>
                Key Features
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
                {features.map((feature, index) => (
                    <div
                        key={index}
                        className="bg-slate-800 rounded-xl border border-slate-700 p-6 hover:border-emerald-500/30 transition-all duration-300 group"
                    >
                        <div className="text-4xl mb-4">{feature.icon}</div>
                        <h3 className="text-lg font-bold text-white mb-2 group-hover:text-emerald-400 transition-colors">
                            {feature.title}
                        </h3>
                        <p className="text-gray-400 text-sm">{feature.description}</p>
                    </div>
                ))}
            </div>

            {/* CTA Section */}
            <div className="bg-gradient-to-r from-emerald-600 to-cyan-600 rounded-2xl p-8 text-center">
                <h3 className="text-2xl font-bold text-white mb-4">Ready to explore?</h3>
                <p className="text-emerald-100 mb-6">Check out the latest match predictions and league standings</p>
                <Link
                    to="/matches"
                    className="inline-block px-8 py-3 bg-white text-emerald-600 font-bold rounded-xl hover:bg-gray-100 transition-colors"
                >
                    Get Started
                </Link>
            </div>
        </div>
    )
}

export default LandingPage
